name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.1.4
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.0.0
  x509: ^0.2.0
  jose: ^0.3.0
  dotenv: ^3.0.0-nullsafety.0
  openid_client: ^0.4.0
  path: ^1.6.4
  meta: ^1.1.6
  http: ^0.13.1
  crypto_keys: ^0.2.0
  collection: ^1.14.11
dev_dependencies:
  test: ^1.0.0
  fake_async: ^1.0.0
  pedantic: ^1.9.0
  mockito: ^5.0.3
